

services:
  node-api:
    build: .
    container_name: node-api-prod
    ports:
      - "3005:8080"
    environment:
      - NODE_ENV=production
      - NEW_RELIC_LICENSE_KEY=${03dac8586fab61361232df1b233e77d1FFFFNRAL}

